version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:26500"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  zeebe:
    image: camunda/zeebe:0.22.0-alpha1
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_PORT=26500
